### ISSUE TITLE
Support CoreCLR

### ISSUE THREAD

**Issue by mholo65** [draylundy/ProtobufGenerator#3]
CoreCLR could be supported.

In order to support CoreCLR, [Sprache](https://github.com/Sprache/Sprache) needs to support CoreCLR. I could check into this.

To benefit from ProtobufGenerator supporting CoreCLR, also [Protobuf-net](https://github.com/mgravell/protobuf-net) needs to support CoreCLR. That, on the other hand could be more tricky as AFAIK [corefx](https://github.com/dotnet/corefx) doesn't yet contain all required dependencies. Hopefully they will be in RC. I have a compiling branch of Protobuf-net [here](https://github.com/mholo65/protobuf-net/tree/CoreCLR), but there are tons of failing Unit Tests.

**Comment by draylundy** [comment]
Yes, hopefully those dependencies will get sorted out (among others) and Protobuf-net can move forward. In any case, we are now building on the CoreCLR with the removal of Sprache and the resolution not to take another outside dependency, so I'm going to close this issue. 

File based unit tests are of course failing as expected, but there is some work to be done there anyway as it's meaningless to test .NET file loading. I hope that's already tested working. =)

I should create some abstraction that allows testing without a real file.
