### ISSUE TITLE
Use CI and create build script

### ISSUE THREAD

**Issue by mholo65** [draylundy/ProtobufGenerator#4]
Use a CI system that is for open source project. Two alternatives are [Travis](https://travis-ci.com/plans) or [Appveyor](http://www.appveyor.com/pricing), there might be other alternatives.

Build scripts should be x-plat, use e.g. [Sake](https://github.com/Sakeproject/sake), and bootstrap using platform specific files (build.cmd, build.sh). CI server should build and run tests on both Linux and Windows.

I have somewhat experience using Sake and would be glad to help out.

**Comment by mholo65** [comment]
#6 Initial build scripts here, using bootstrapper (sh/cmd) and Sake 0.2.2.

**Comment by draylundy** [comment]
Good suggestion. Went with both Travis and Appveyor to get a build on Ubuntu Server and one on Windows Server. 

Thanks for the work you've done on the build scripts. Saved me quite a bit of time.
