### ISSUE TITLE
Evaluation of Compiler Project : Development Plan

### ISSUE THREAD

**Issue by draylundy** [draylundy/ProtobufGenerator#5]
### Difficulties with Sprache

Hit a bit of a wall with Sprache and the strong typing approach and wasn't real happy with the workarounds. 

Specifically, once we get to the Message definition we can have many different types of definitions inside the block scope of the message and they can not only be in any order but we can also have nested Message and Enum definitions. That provides some difficulty since the goal here was using strong typed return values from Parsers; i.e. if you want to do a ``.Many()`` or ``.Or()`` relationship you need to be returning the same ``T`` for ``IEnumerable<T>``. 

### Possible Hackish Workaround
The first attempt at a workaround removed the strong typing from all definitions inside the message block scope and return them as strings, using the ``;`` as terminators for single line declarations and catching lines which end in ``{`` and continuing to process until a ``}`` character to catch nested definitions, with the goal of doing some imperative Parser processing via looping construct. 

However, that gets you ``IEnumerable<Parser<T>>``, instead of  ``IEnumerable<T>``, and while you can try to ``.Invoke()`` the parsers standalone outside of the Monadic Parser Combinator pattern I couldn't get it to work very well. Perhaps it's not the tool for this job. 

Overall what seemed like a good idea at the start with that workaround began to look like a very fragile solution that would have to constantly be revisited. With no other clear way forward the Sprache implementation is at a blocking point. 

### Alternative Thoughts
Over the past couple days I've been giving some thought to switching out to a parser generator like ANTLR where we can just plug and chug with an EBNF grammar or another .NET native managed parser. 

Unfortunately with cross-platform goals an industrial strength parser generator is not an option. C# doesn't seem to be a first class citizen for most of those generators and I think it might be some time before they go cross platform with the C# runtime if at all. 

Another .NET native library might be a path of least resistance but looking over the options it seems like there is not a clear best of breed and in any case it seems like it might be a mistake to leverage an outside library for core functionality. 

### Plan Going Forward

Updated 15.Oct.2015

1. Short Term
  - [x] Create new ``SpracheLegacy`` branch from current ``Master``. 
  - [x] Remove Sprache dependency and move to cross platform. 
  - [x] Begin work on the *front end* class generator Template that we can project the ``FileDescriptor``'s into to generate the class files. 

2. Long Term
  - [ ] Develop own managed compiler for .proto definition files into ``FileDescriptorSet`` representation. 
    - [X] Lexical Analyzer
    - [x] Syntax Analyzer
    - [x] Semantic Analyzer

**Comment by draylundy** [comment]
Looking into using the protoc tool, seems the options aren't too friendly. 

We could output a binary protocol buffer that we could then read into a FileDescriptorSet, but this requires support of existing Protobuf-net serializer. Aside from that tooling not yet being x-plat I'm not quite comfortable with introducing circular dependency even in a *bootstrapping* scenario. 

Think the best option going forward is the fully managed compiler using multiple passes on the Syntax Analyzer. End product would be an AST that we can either use to generate class files directly via Roslyn and some visitor pattern (even possible with Roslyn immutability of elements?) or project into a text template to give more control over the formatting and provide any features that Roslyn doesn't.

**Comment by mholo65** [comment]
Are there any specific parts I could look into?

**Comment by draylundy** [comment]
Going to wrap this issue up. Fresh eyes have new vision and Github has implemented the Project management feature in the interim.
